config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :book_lists do
    resources :books, only: [:new, :create, :edit, :update, :destroy]
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "book_lists#index"
  get "/about",to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :bookTitle, :author, :description, :price, presence: { message: "Please complete the form." }
    belongs_to :book_list
end

app/models/book_list.rb
class BookList < ApplicationRecord
    validates :title, :listDescription, presence: true, format: { without: /\A\d+\z/, message: "Input must be a string." }
    validates :title, presence: { message: "Please include the title." }
    validates :listDescription, presence: { message: "Please include the list description." }

    has_many :books, dependent: :destroy
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, :password, :password_confirmation, presence: { message: "Please enter a value." }
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "Email must be written in the correct format ([name]@[mailservice].com)" }
  validates :password, presence: true, length: { minimum: 6, message: "Password must have a minimum of 6 characters." }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :book_lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include Pagy::Backend
end

app/controllers/book_lists_controller.rb
class BookListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book_list, only: %i[ show edit update destroy ]
  # GET /book_lists or /book_lists.json
  def index
    @list_pagy, @book_lists = pagy(current_user.book_lists, items: 9)
  end

  # GET /book_lists/1 or /book_lists/1.json
  def show
    @book_list = current_user.book_lists.find(params[:id])
    @list_pagy, @books = pagy(@book_list.books, items: 10)
  end

  # GET /book_lists/new
  def new
    @book_list = current_user.book_lists.new
  end

  # GET /book_lists/1/edit
  def edit
  end

  # POST /book_lists or /book_lists.json
  def create
    @book_list = current_user.book_lists.new(book_list_params)
    if @book_list.title =~ /\A\d+\z/
      flash.now[:alert] = "Please enter a valid string for the list title, not a number."
      render :new and return
    end
    if @book_list.listDescription =~ /\A\d+\z/
      flash.now[:alert] = "Please enter a valid string for the list description, not a number."
      render :new and return
    end
    respond_to do |format|
      if @book_list.save
        format.html { redirect_to @book_list, notice: "Book list was successfully created." }
        format.json { render :show, status: :created, location: @book_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_list.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /book_lists/1 or /book_lists/1.json
  def update
    respond_to do |format|
      if @book_list.update(book_list_params)
        format.html { redirect_to @book_list, notice: "Book list was successfully updated." }
        format.json { render :show, status: :ok, location: @book_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_lists/1 or /book_lists/1.json
  def destroy
    @book_list.destroy!

    respond_to do |format|
      format.html { redirect_to book_lists_path, status: :see_other, notice: "Book list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_list
      @book_list = current_user.book_lists.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def book_list_params
      params.require(:book_list).permit(:title, :listDescription)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book_list
  before_action :set_book, only: [ :edit, :update, :destroy ]

  # GET /books/new
  def new
    @book = @book_list.books.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = @book_list.books.build(book_params)
    if @book.save
      redirect_to @book_list, notice: "Book was successfully added."
    else
      render :new
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book_list, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to book_list_path, status: :see_other, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_list
      @book_list = BookList.find(params[:book_list_id])
    end
    def set_book
    @book = @book_list.books.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Book not found."
    redirect_to book_list_path(@book_list)
  end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:bookTitle, :author, :description, :price)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/book_lists_helper.rb
module BookListsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/book_lists/_book_list.html.erb
<% if alert %>
   <div class="alert alert-danger">
         <%= alert %>
   </div>
<% end %>

<h2>  <%= book_list.title %> </h2>
<p>  <%= book_list.listDescription %> </p>
<hr>
<% if @books.exists? %>
<table class="table">
   <thead>
       <tr>
            <th> Position   </th>
            <th> Book title </th>
            <th> Author </th>
            <th> Description </th>
            <th> Price </th>
            <th> Options </th>
       </tr>
   </thead>
 
   <tbody>
       <% @books.each.with_index do |book, index| %>
        <tr>
           <td> <%= index + 1 %> </td>
           <td> <%= book.bookTitle %> </td>
           <td> <%= book.author %> </td>
           <td> <%= book.description %> </td>
           <td> $ <%= book.price %> </td>
           <td class="d-flex gap-2">
              <%= link_to "Edit", edit_book_list_book_path(@book_list, book), class: "btn btn-danger btn-sm" %>
              <%= button_to "Delete", book_list_book_path(@book_list, book), method: :delete, class: "btn btn-danger btn-sm" %>        
              </td>
        </tr>
       <% end %>     
   </tbody>
</table>

<% else %>
   <p> No books to display. </p>
<% end %>

<%= link_to "Add a book", new_book_list_book_path(@book_list), class: "btn btn-danger" %>
<div class="nav justify-content-center">
    <% if @list_pagy&.pages.to_i > 1 %>
  <%= pagy_bootstrap_nav(@list_pagy).html_safe %>
<% end %>

</div>

app/views/book_lists/_form.html.erb
<%= form_with(model: book_list) do |form| %>
  <% if book_list.errors.any? %>
    <div style="color: red">
      <ul>
        <% book_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, required: true, class: "form-control" %>

    <%= form.label :listDescription, style: "display: block" %>
    <%= form.text_field :listDescription, required: true, class: "form-control" %>
  </div>

  <div class="mt-2">
    <%= form.submit class: "btn btn-danger" %>
  </div>

<% end %>

app/views/book_lists/edit.html.erb
<% content_for :title, "Editing book list" %>
<div class="container mt-5">
<h1>Editing book list</h1>

<%= render "form", book_list: @book_list %>

<br>
</div>
<div class="nav align-items-center justify-content-center gap-2">
  <%= link_to "Show this book list", @book_list, class: "btn btn-danger" %> 
  <%= link_to "Back to book lists", book_lists_path, class: "btn btn-danger" %>
</div>

app/views/book_lists/index.html.erb
<% if notice %>
<p class="alert alert-success" style="color: green"><%= notice %></p>
<% end %>
<% content_for :title, "Book lists" %>

<div class="container mt-5">
<div class="nav justify-content-between align-items-center">
   <h1>Book lists</h1>
   <%= link_to "Create new list", new_book_list_path , class: "btn btn-danger" %>
</div>
<hr>

<div class="row">
      <% @book_lists.each do |book_list| %>
      <div class="col-12 col-sm-6 col-md-4 mt-3">
         <div class="card border-0 shadow shadow-md">
   <div class="card-body">
       <h3 class="card-title"> <%= book_list.title %> </h3>
       <p class="card-description"> <%= book_list.listDescription %> </p>
       <div class="card-footer d-flex gap-2 justify-content-end">
       <%= link_to "Open", book_list, class: "btn btn-danger btn-sm" %>
       <%= link_to "Edit", edit_book_list_path(book_list), class: "btn btn-danger btn-sm" %>
       <%= button_to "Delete", book_list, method: :delete, data: { turbo_confirm: "Are you sure you want to delete this book?"}, class: "btn btn-danger btn-sm"%>
       </div>
   </div>

</div>
     </div>     
       <% end %>
</div>
<div class="d-flex justify-content-center mt-3">
   <% if @list_pagy&.pages.to_i > 1 %>
  <%= pagy_bootstrap_nav(@list_pagy).html_safe %>
<% end %>

  </div>
</div>

app/views/book_lists/new.html.erb
<% content_for :title, "New book list" %>
<% if flash[:alert] %>
   <div class="alert alert-danger">
       <%= flash[:alert] %>
   </div>
<% end %>
<div class="container mt-5">
<h1>New book list</h1>
<hr>
<%= render "form", book_list: @book_list %>
<div>
  <%= link_to "Back to book lists", book_lists_path, class: "btn btn-danger mt-3" %>
</div>
</div>

app/views/book_lists/show.html.erb
<% if notice %>
<p class="alert alert-success" style="color: green"><%= notice %></p>
<% end %>


<div class="container mt-5">
<%= render @book_list %>
<div class="nav align-items-center justify-content-center gap-2">
  
  <%= link_to "Back to book lists", book_lists_path, class: "btn btn-danger"%>
  
</div>
</div>

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Booktitle:</strong>
    <%= book.bookTitle %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= book.price %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: [@book_list, @book]) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="d-flex flex-column gap-2">
  <div>
    <%= form.label :bookTitle, style: "display: block" %>
    <%= form.text_field :bookTitle, required: true, class: "form-control"%>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author, required: true, class: "form-control"%>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description, required: true, class: "form-control" %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, required: true, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-danger" %>
  </div>
</div>
<% end %>

app/views/books/edit.html.erb
<% content_for :title, "Editing book" %>


<div class="container mt-5">
<h1>Editing book</h1>
<%= render "form", book: @book %>
</div>
<br>

<div class="d-flex gap-2 justify-content-center">
  <%= link_to "Back to books", @book_list, class: "btn btn-danger"%>
</div>

app/views/books/new.html.erb
<% content_for :title, "New book" %>
<div class="container mt-5">
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", @book_list, class: "btn btn-danger" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bookstore Ims" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= render "shared/navbar", user: current_user%>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container mt-5">
<h2> About page </h2>
<hr>
<div class="accordion" id="aboutAccordion">
  <div class="accordion-item border-0">
    <h2 class="accordion-header">
      <button class="accordion-button bg-danger text-white" type="button" data-bs-toggle="collapse" data-bs-target="#about1" aria-expanded="true" aria-controls="about1">
          What is this app?
      </button>
    </h2>
    <div id="about1" class="accordion-collapse collapse show" data-bs-parent="#aboutAccordion">
      <div class="accordion-body">
          MyBrary is a wishlist management system where you can create lists of books that pertain to a specific topic or category of books.
          You may use this software to keep inventory of books you are interested in or rank your top books by genre. The possibilities are endless.
      </div>
    </div>
  </div>
  <div class="accordion-item border-0">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-danger text-white" type="button" data-bs-toggle="collapse" data-bs-target="#about2" aria-expanded="false" aria-controls="about2">
      Why did I make this?
      </button>
    </h2>
    <div id="about2" class="accordion-collapse collapse" data-bs-parent="#aboutAccordion">
      <div class="accordion-body">
        A few years ago, I wrote an incomplete Java swing desktop app for a school assignment that spanned throughout my software design and architecture course.
        Although I learned how to use the swing GUI framework and database interaction with MySQL, it was left with bugs and I was therefore not pleased with its state.
        I also did not enjoy writing in Java while in college due to how heavy, verbose and religiously insistent on OOP it was, making it a dull language to work with.
        However, I left it alone for the past few years until recently when I decided to revisit ruby on rails. I felt that Ruby on Rails convention over configuration 
        philosophy presented a perfect opportunity for me to change from Java to Ruby as a third language. Therefore, I decided to redo my bookstore IMS into a more
        useful, complete app that can also be deployed to production for others to try out. 
      </div>
    </div>
  </div>
  <div class="accordion-item border-0">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed bg-danger text-white" type="button" data-bs-toggle="collapse" data-bs-target="#about3" aria-expanded="false" aria-controls="about3">
        What are some future plans for this app?
      </button>
    </h2>
    <div id="about3" class="accordion-collapse collapse" data-bs-parent="#aboutAccordion">
      <div class="accordion-body">
        Although this app was mostly meant to replace an old, unpolished school project with a complete, robust app, I do have a couple more plans in mind for the forseeable future. 
        <ul>
             <li> User profile pictures: Add your own picture for your page. </li>
             <li> Export as CSV: Export CSV file of list to share with others, keep track of books elsewhere etc. </li>
             <li> Link to book: Link to site where you plan to buy a book </li>
        </ul>
      </div>
    </div>
  </div>
</div>

</div>

app/views/shared/_footer.html.erb
<footer class="footer-body text-center mt-5">
  <small class="text-sm opacity-50"> Sebastian Chalarca, MyBrary @2025 All Rights Reserved </small>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-dark text-danger p-2 shadow shadow-md">
   <div class="container">
     <h1> <i class="bi bi-book-half"></i> MyBrary </h1>
     <div class="nav gap-2 align-items-center">
      <%= link_to "My lists", book_lists_path, class: "btn btn-danger"%>
         <%= link_to "About", "/about" ,class: "btn btn-danger" %>
         <% if current_user %>
            <div class="dropdown">
            <button class="dropdown-toggle btn btn-danger" data-bs-toggle="dropdown" data-bs-target="#profile-dropdown"> Welcome, <%= current_user.email %> ! </button>
            <ul class="dropdown-menu" id="profile-dropdown">
                 <li class="dropdown-item">
  <%= button_to "Delete my account",
              registration_path(current_user),
              method: :delete,
              data: { turbo_confirm: "Are you sure you want to delete your account? This cannot be undone." },
              class: "btn btn-link text-black dropdown-item p-0" %>
</li>

<li class="dropdown-item">
  <li class="dropdown-item">
  <%= button_to "Log out",
                destroy_user_session_path,
                method: :delete,
                data: { turbo_confirm: "Are you sure you want to log out?" },
                class: "btn btn-link text-black dropdown-item p-0" %>
</li>

</li>

            </ul> 
           </div>
         <% end %>
     </div>
   </div>
</nav>